inputDataDirectory: C:/Users/Administrator/OneDrive - WU Wien/Desktop/GUCON-Obl/emrDatabase/mapped/emrGraph-100.ttl
inputTime: 2010-01-10T10:44:00.000+02:00
outputRuleDirectory: C:/Users/Administrator/OneDrive - WU Wien/Desktop/GUCON-Obl/generatedData/rules/
outputKBDirectory: C:/Users/Administrator/OneDrive - WU Wien/Desktop/GUCON-Obl/generatedData/kb/
ruleScale: 
 - 5
 - 9
 - 13
 - 17
 - 21
KBScale: 
 - 100000
 - 208000
 - 406000
 - 604000
 - 802000
 - 1000000

